---
- name: Deploy Apache HTTP Server via AAP (Ingress Allowed, Internet Blocked)
  hosts: localhost
  connection: local
  gather_facts: no

  vars:
    ############################################################
    # TEMPLATE DETAILS
    ############################################################
    template_name: httpd-example
    template_namespace: openshift

    ############################################################
    # APPLICATION (FROM SURVEY)
    ############################################################
    app_name: "{{ app_name }}"
    runtime_namespace: "{{ runtime_namespace }}"
    httpd_version: "{{ httpd_version }}"
    memory_limit: "{{ memory_limit }}"
    git_repo_url: "{{ git_repo_url }}"

    ############################################################
    # NETWORK SETTINGS
    ############################################################
    app_port: 8080
    ingress_namespace: openshift-ingress
    route_host: "{{ app_name }}.apps.pgrhoso.dccloud.com"

  tasks:

    ############################################################
    # 1️⃣ Process Apache HTTPD Template
    ############################################################
    - name: Process Apache HTTPD template
      community.okd.openshift_process:
        name: "{{ template_name }}"
        namespace: "{{ template_namespace }}"
        namespace_target: "{{ runtime_namespace }}"
        parameters:
          NAME: "{{ app_name }}"
          NAMESPACE: "{{ template_namespace }}"
          HTTPD_VERSION: "{{ httpd_version }}"
          MEMORY_LIMIT: "{{ memory_limit }}"
          SOURCE_REPOSITORY_URL: "{{ git_repo_url }}"
      register: apache_template

    ############################################################
    # 2️⃣ Apply Generated Resources
    ############################################################
    - name: Create application resources
      community.okd.k8s:
        state: present
        namespace: "{{ runtime_namespace }}"
        definition: "{{ item }}"
      loop: "{{ apache_template.resources }}"

    ############################################################
    # 3️⃣ Create Route (Ingress)
    ############################################################
    - name: Create OpenShift Route
      community.okd.k8s:
        state: present
        namespace: "{{ runtime_namespace }}"
        definition:
          apiVersion: route.openshift.io/v1
          kind: Route
          metadata:
            name: "{{ app_name }}"
          spec:
            host: "{{ route_host }}"
            to:
              kind: Service
              name: "{{ app_name }}"
            port:
              targetPort: "{{ app_port }}"
            tls:
              termination: edge

    ############################################################
    # 4️⃣ NetworkPolicy – BLOCK INTERNET, ALLOW DNS + GITHUB
    ############################################################
    - name: Apply NetworkPolicy (App Pods Only)
      community.okd.k8s:
        state: present
        namespace: "{{ runtime_namespace }}"
        definition:
          apiVersion: networking.k8s.io/v1
          kind: NetworkPolicy
          metadata:
            name: "{{ app_name }}-restricted-egress"
          spec:
            podSelector:
              matchLabels:
                app: "{{ app_name }}"

            policyTypes:
              - Ingress
              - Egress

            ####################################################
            # INGRESS: Allow OpenShift Router
            ####################################################
            ingress:
              - from:
                  - namespaceSelector:
                      matchLabels:
                        kubernetes.io/metadata.name: "{{ ingress_namespace }}"
                ports:
                  - protocol: TCP
                    port: "{{ app_port }}"

            ####################################################
            # EGRESS:
            # ✅ DNS allowed
            # ✅ HTTPS (GitHub) allowed
            # ❌ Internet blocked
            ####################################################
            egress:
              # DNS
              - ports:
                  - protocol: UDP
                    port: 53
                  - protocol: TCP
                    port: 53

              # HTTPS (GitHub)
              - ports:
                  - protocol: TCP
                    port: 443

    ############################################################
    # 5️⃣ Restart Deployment (Apply Policy)
    ############################################################
    - name: Restart deployment to apply NetworkPolicy
      kubernetes.core.k8s:
        state: patched
        api_version: apps/v1
        kind: Deployment
        name: "{{ app_name }}"
        namespace: "{{ runtime_namespace }}"
        merge_type: strategic-merge
        definition:
          spec:
            template:
              metadata:
                annotations:
                  restartedAt: "{{ lookup('pipe', 'date +%s') }}"
