---
- name: Deploy Apache HTTP Server via AAP (Survey + Robust NetworkPolicy)
  hosts: localhost
  connection: local
  gather_facts: no

  ############################################################
  # SURVEY VARIABLES (PLAIN STRINGS)
  ############################################################
  vars:
    app_name: "{{ app_name }}"
    runtime_namespace: "{{ runtime_namespace }}"
    httpd_version: "{{ httpd_version }}"
    memory_limit: "{{ memory_limit }}"
    git_repo_url: "{{ git_repo_url }}"

    ingress_cidrs: "{{ ingress_cidrs }}"     # 0.0.0.0/0
    ingress_ports: "{{ ingress_ports }}"     # TCP:8080
    egress_cidrs: "{{ egress_cidrs }}"       # 0.0.0.0/0
    egress_ports: "{{ egress_ports }}"       # UDP:53, TCP:53, TCP:443

    template_name: httpd-example
    template_namespace: openshift
    app_port: 8080
    route_host: "{{ app_name }}.apps.pgrhoso.dccloud.com"

  tasks:

    ############################################################
    # 1️⃣ PROCESS TEMPLATE
    ############################################################
    - name: Process Apache HTTPD template
      community.okd.openshift_process:
        name: "{{ template_name }}"
        namespace: "{{ template_namespace }}"
        namespace_target: "{{ runtime_namespace }}"
        parameters:
          NAME: "{{ app_name }}"
          NAMESPACE: "{{ template_namespace }}"
          HTTPD_VERSION: "{{ httpd_version }}"
          MEMORY_LIMIT: "{{ memory_limit }}"
          SOURCE_REPOSITORY_URL: "{{ git_repo_url }}"
      register: apache_template

    ############################################################
    # 2️⃣ APPLY RESOURCES
    ############################################################
    - name: Create application resources
      community.okd.k8s:
        state: present
        namespace: "{{ runtime_namespace }}"
        definition: "{{ item }}"
      loop: "{{ apache_template.resources }}"

    ############################################################
    # 3️⃣ CREATE ROUTE
    ############################################################
    - name: Create OpenShift Route
      community.okd.k8s:
        state: present
        namespace: "{{ runtime_namespace }}"
        definition:
          apiVersion: route.openshift.io/v1
          kind: Route
          metadata:
            name: "{{ app_name }}"
          spec:
            host: "{{ route_host }}"
            to:
              kind: Service
              name: "{{ app_name }}"
            port:
              targetPort: "{{ app_port }}"
            tls:
              termination: edge

    ############################################################
    # 4️⃣ BUILD NETWORK POLICY STRUCTURES (NATIVE, SAFE)
    ############################################################

    - name: Init ingress ports list
      set_fact:
        ingress_ports_parsed: []

    - name: Init egress ports list
      set_fact:
        egress_ports_parsed: []

    - name: Init ingress cidr list
      set_fact:
        ingress_from_blocks: []

    - name: Init egress cidr list
      set_fact:
        egress_to_blocks: []

    - name: Build ingress ports
      set_fact:
        ingress_ports_parsed: "{{ ingress_ports_parsed + [ {'protocol': item.split(':')[0] | upper, 'port': item.split(':')[1] | int } ] }}"
      loop: "{{ ingress_ports.split(',') | map('trim') | list }}"

    - name: Build egress ports
      set_fact:
        egress_ports_parsed: "{{ egress_ports_parsed + [ {'protocol': item.split(':')[0] | upper, 'port': item.split(':')[1] | int } ] }}"
      loop: "{{ egress_ports.split(',') | map('trim') | list }}"

    - name: Build ingress CIDRs
      set_fact:
        ingress_from_blocks: "{{ ingress_from_blocks + [ {'ipBlock': {'cidr': item}} ] }}"
      loop: "{{ ingress_cidrs.split(',') | map('trim') | list }}"

    - name: Build egress CIDRs
      set_fact:
        egress_to_blocks: "{{ egress_to_blocks + [ {'ipBlock': {'cidr': item}} ] }}"
      loop: "{{ egress_cidrs.split(',') | map('trim') | list }}"

    ############################################################
    # 5️⃣ APPLY NETWORK POLICY
    ############################################################
    - name: Apply NetworkPolicy (FINAL SAFE VERSION)
      community.okd.k8s:
        state: present
        namespace: "{{ runtime_namespace }}"
        definition:
          apiVersion: networking.k8s.io/v1
          kind: NetworkPolicy
          metadata:
            name: "{{ app_name }}-network-policy"
          spec:
            podSelector:
              matchLabels:
                name: "{{ app_name }}"
            policyTypes:
              - Ingress
              - Egress
            ingress:
              - from: "{{ ingress_from_blocks }}"
                ports: "{{ ingress_ports_parsed }}"
            egress:
              - to: "{{ egress_to_blocks }}"
                ports: "{{ egress_ports_parsed }}"

    ############################################################
    # 6️⃣ FORCE POD RESTART
    ############################################################
    - name: Force rollout restart
      kubernetes.core.k8s:
        state: patched
        api_version: apps/v1
        kind: Deployment
        name: "{{ app_name }}"
        namespace: "{{ runtime_namespace }}"
        merge_type: strategic-merge
        definition:
          spec:
            template:
              metadata:
                annotations:
                  restartedAt: "{{ lookup('pipe', 'date +%s') }}"
