---
- name: Deploy Apache HTTP Server via AAP (Secure Runtime, Internet Blocked)
  hosts: localhost
  connection: local
  gather_facts: no

  ############################################################
  # VARIABLES (FROM SURVEY)
  ############################################################
  vars:
    # OpenShift template
    template_name: httpd-example
    template_namespace: openshift

    # Application (survey driven)
    app_name: "{{ app_name }}"
    runtime_namespace: "{{ runtime_namespace }}"
    httpd_version: "{{ httpd_version }}"
    memory_limit: "{{ memory_limit }}"
    git_repo_url: "{{ git_repo_url }}"

    # Networking
    app_port: 8080
    ingress_namespace: openshift-ingress
    route_host: "{{ app_name }}.apps.pgrhoso.dccloud.com"

  tasks:

    ############################################################
    # 1️⃣ Process Apache HTTPD Template (BUILD PHASE)
    ############################################################
    - name: Process Apache HTTPD template
      community.okd.openshift_process:
        name: "{{ template_name }}"
        namespace: "{{ template_namespace }}"
        namespace_target: "{{ runtime_namespace }}"
        parameters:
          NAME: "{{ app_name }}"
          NAMESPACE: "{{ template_namespace }}"
          HTTPD_VERSION: "{{ httpd_version }}"
          MEMORY_LIMIT: "{{ memory_limit }}"
          SOURCE_REPOSITORY_URL: "{{ git_repo_url }}"
      register: apache_template

    ############################################################
    # 2️⃣ Apply Generated Resources
    ############################################################
    - name: Create application resources
      community.okd.k8s:
        state: present
        namespace: "{{ runtime_namespace }}"
        definition: "{{ item }}"
      loop: "{{ apache_template.resources }}"

    ############################################################
    # 3️⃣ Wait until runtime pod is READY
    ############################################################
    - name: Wait for application pod to be running
      kubernetes.core.k8s_info:
        kind: Pod
        namespace: "{{ runtime_namespace }}"
        label_selectors:
          - "name={{ app_name }}"
      register: pod_info
      until: >
        pod_info.resources | length > 0 and
        pod_info.resources[0].status.phase == "Running"
      retries: 30
      delay: 10

    ############################################################
    # 4️⃣ Create Route (Ingress)
    ############################################################
    - name: Create OpenShift Route
      community.okd.k8s:
        state: present
        namespace: "{{ runtime_namespace }}"
        definition:
          apiVersion: route.openshift.io/v1
          kind: Route
          metadata:
            name: "{{ app_name }}"
          spec:
            host: "{{ route_host }}"
            to:
              kind: Service
              name: "{{ app_name }}"
            port:
              targetPort: "{{ app_port }}"
            tls:
              termination: edge

    ############################################################
    # 5️⃣ NetworkPolicy – APPLY ONLY TO RUNTIME PODS
    #     (Build pods are NOT affected)
    ############################################################
    - name: Apply NetworkPolicy (Block Internet for Runtime Pods)
      community.okd.k8s:
        state: present
        namespace: "{{ runtime_namespace }}"
        definition:
          apiVersion: networking.k8s.io/v1
          kind: NetworkPolicy
          metadata:
            name: "{{ app_name }}-runtime-restricted-egress"
          spec:
            podSelector:
              matchLabels:
                name: "{{ app_name }}"   # runtime pods ONLY

            policyTypes:
              - Ingress
              - Egress

            ############################
            # INGRESS: OpenShift Router
            ############################
            ingress:
              - from:
                  - namespaceSelector:
                      matchLabels:
                        kubernetes.io/metadata.name: "{{ ingress_namespace }}"
                ports:
                  - protocol: TCP
                    port: "{{ app_port }}"

            ############################
            # EGRESS: DNS + INTERNAL ONLY
            ############################
            egress:
              # DNS (mandatory)
              - to:
                  - namespaceSelector:
                      matchLabels:
                        kubernetes.io/metadata.name: openshift-dns
                ports:
                  - protocol: UDP
                    port: 53
                  - protocol: TCP
                    port: 53

              # Internal cluster ranges
              - to:
                  - ipBlock:
                      cidr: 10.0.0.0/8
              - to:
                  - ipBlock:
                      cidr: 172.16.0.0/12
              - to:
                  - ipBlock:
                      cidr: 192.168.0.0/16
