---
- name: Deploy Apache HTTP Server via AAP (Same App Name → New Pod)
  hosts: localhost
  connection: local
  gather_facts: no

  vars:
    ############################################################
    # OPENSHIFT TEMPLATE DETAILS
    ############################################################
    template_name: httpd-example
    template_namespace: openshift

    ############################################################
    # SURVEY INPUTS
    ############################################################
    app_name: "{{ app_name }}"
    runtime_namespace: "{{ runtime_namespace }}"
    httpd_version: "{{ httpd_version }}"
    memory_limit: "{{ memory_limit }}"
    git_repo_url: "{{ git_repo_url }}"

    ############################################################
    # NETWORK
    ############################################################
    app_port: 8080
    ingress_namespace: openshift-ingress
    route_host: "{{ app_name }}.apps.pgrhoso.dccloud.com"

  tasks:

    ############################################################
    # 1️⃣ PROCESS APACHE TEMPLATE
    ############################################################
    - name: Process Apache HTTPD template
      community.okd.openshift_process:
        name: "{{ template_name }}"
        namespace: "{{ template_namespace }}"
        namespace_target: "{{ runtime_namespace }}"
        parameters:
          NAME: "{{ app_name }}"
          NAMESPACE: "{{ template_namespace }}"
          HTTPD_VERSION: "{{ httpd_version }}"
          MEMORY_LIMIT: "{{ memory_limit }}"
          SOURCE_REPOSITORY_URL: "{{ git_repo_url }}"
      register: apache_template

    ############################################################
    # 2️⃣ APPLY GENERATED RESOURCES
    ############################################################
    - name: Create application resources
      community.okd.k8s:
        state: present
        namespace: "{{ runtime_namespace }}"
        definition: "{{ item }}"
      loop: "{{ apache_template.resources }}"

    ############################################################
    # 3️⃣ CREATE ROUTE (INGRESS)
    ############################################################
    - name: Create OpenShift Route
      community.okd.k8s:
        state: present
        namespace: "{{ runtime_namespace }}"
        definition:
          apiVersion: route.openshift.io/v1
          kind: Route
          metadata:
            name: "{{ app_name }}"
          spec:
            host: "{{ route_host }}"
            to:
              kind: Service
              name: "{{ app_name }}"
            port:
              targetPort: "{{ app_port }}"
            tls:
              termination: edge

    ############################################################
    # 4️⃣ NETWORK POLICY – INTERNET RESTRICTED
    ############################################################
    - name: Apply NetworkPolicy (DNS + HTTPS only)
      community.okd.k8s:
        state: present
        namespace: "{{ runtime_namespace }}"
        definition:
          apiVersion: networking.k8s.io/v1
          kind: NetworkPolicy
          metadata:
            name: "{{ app_name }}-restricted-egress"
          spec:
            podSelector: {}   # applies to ALL pods of this app
            policyTypes:
              - Ingress
              - Egress

            # Ingress: only from OpenShift router
            ingress:
              - from:
                  - namespaceSelector:
                      matchLabels:
                        kubernetes.io/metadata.name: "{{ ingress_namespace }}"
                ports:
                  - protocol: TCP
                    port: "{{ app_port }}"

            # Egress: DNS + HTTPS ONLY
            egress:
              - to:
                  - ipBlock:
                      cidr: 0.0.0.0/0
                ports:
                  - protocol: UDP
                    port: 53
                  - protocol: TCP
                    port: 53

              - to:
                  - ipBlock:
                      cidr: 0.0.0.0/0
                ports:
                  - protocol: TCP
                    port: 443

    ############################################################
    # 5️⃣ FORCE ROLLOUT → ALWAYS CREATE NEW POD
    ############################################################
    - name: Force rollout to create NEW pod (same app name)
      kubernetes.core.k8s:
        state: patched
        api_version: apps/v1
        kind: Deployment
        name: "{{ app_name }}"
        namespace: "{{ runtime_namespace }}"
        merge_type: strategic-merge
        definition:
          spec:
            template:
              metadata:
                annotations:
                  rollout-trigger: "{{ lookup('pipe', 'date +%s') }}"
