---
- name: Deploy Apache HTTP Server via AAP (New App = New Pod)
  hosts: localhost
  connection: local
  gather_facts: no

  vars:
    ############################################################
    # OPENSHIFT TEMPLATE DETAILS
    ############################################################
    template_name: httpd-example
    template_namespace: openshift

    ############################################################
    # APPLICATION (FROM SURVEY)
    ############################################################
    app_name: "{{ app_name }}"
    runtime_namespace: "{{ runtime_namespace }}"
    httpd_version: "{{ httpd_version }}"
    memory_limit: "{{ memory_limit }}"
    git_repo_url: "{{ git_repo_url }}"

    ############################################################
    # NETWORK SETTINGS
    ############################################################
    app_port: 8080
    ingress_namespace: openshift-ingress
    route_host: "{{ app_name }}.apps.pgrhoso.dccloud.com"

  tasks:

    ############################################################
    # 1️⃣ Process Apache HTTPD Template
    ############################################################
    - name: Process Apache HTTPD template
      community.okd.openshift_process:
        name: "{{ template_name }}"
        namespace: "{{ template_namespace }}"
        namespace_target: "{{ runtime_namespace }}"
        parameters:
          NAME: "{{ app_name }}"
          NAMESPACE: "{{ template_namespace }}"
          HTTPD_VERSION: "{{ httpd_version }}"
          MEMORY_LIMIT: "{{ memory_limit }}"
          SOURCE_REPOSITORY_URL: "{{ git_repo_url }}"
      register: apache_template

    ############################################################
    # 2️⃣ Apply Generated Resources
    ############################################################
    - name: Create application resources
      community.okd.k8s:
        state: present
        namespace: "{{ runtime_namespace }}"
        definition: "{{ item }}"
      loop: "{{ apache_template.resources }}"

    ############################################################
    # 3️⃣ Create Route
    ############################################################
    - name: Create OpenShift Route
      community.okd.k8s:
        state: present
        namespace: "{{ runtime_namespace }}"
        definition:
          apiVersion: route.openshift.io/v1
          kind: Route
          metadata:
            name: "{{ app_name }}"
            labels:
              app: "{{ app_name }}"
          spec:
            host: "{{ route_host }}"
            to:
              kind: Service
              name: "{{ app_name }}"
            port:
              targetPort: "{{ app_port }}"
            tls:
              termination: edge

    ############################################################
    # 4️⃣ NetworkPolicy for BUILD PODS (ALLOW INTERNET)
    ############################################################
    - name: Allow internet for build pods
      community.okd.k8s:
        state: present
        namespace: "{{ runtime_namespace }}"
        definition:
          apiVersion: networking.k8s.io/v1
          kind: NetworkPolicy
          metadata:
            name: allow-build-egress
          spec:
            podSelector:
              matchLabels:
                openshift.io/build.name: ""
            policyTypes:
              - Egress
            egress:
              - to:
                  - ipBlock:
                      cidr: 0.0.0.0/0
                ports:
                  - protocol: TCP
                    port: 443
                  - protocol: UDP
                    port: 53
                  - protocol: TCP
                    port: 53

    ############################################################
    # 5️⃣ NetworkPolicy for APP PODS (BLOCK INTERNET)
    ############################################################
    - name: Block internet for application pods
      community.okd.k8s:
        state: present
        namespace: "{{ runtime_namespace }}"
        definition:
          apiVersion: networking.k8s.io/v1
          kind: NetworkPolicy
          metadata:
            name: "{{ app_name }}-deny-internet"
          spec:
            podSelector:
              matchLabels:
                name: "{{ app_name }}"
            policyTypes:
              - Ingress
              - Egress

            ingress:
              - from:
                  - namespaceSelector:
                      matchLabels:
                        kubernetes.io/metadata.name: "{{ ingress_namespace }}"
                ports:
                  - protocol: TCP
                    port: "{{ app_port }}"

            egress:
              - to:
                  - ipBlock:
                      cidr: 10.0.0.0/8
              - to:
                  - ipBlock:
                      cidr: 172.16.0.0/12
              - to:
                  - ipBlock:
                      cidr: 192.168.0.0/16
