---
- name: Deploy Apache HTTP Server via AAP (Survey-driven NetworkPolicy)
  hosts: localhost
  connection: local
  gather_facts: no

  vars:
    ############################################################
    # OPENSHIFT TEMPLATE DETAILS
    ############################################################
    template_name: httpd-example
    template_namespace: openshift

    ############################################################
    # SURVEY VARIABLES (REQUIRED)
    ############################################################
    app_name: "{{ app_name }}"
    runtime_namespace: "{{ runtime_namespace }}"
    httpd_version: "{{ httpd_version }}"
    memory_limit: "{{ memory_limit }}"
    git_repo_url: "{{ git_repo_url }}"

    ############################################################
    # NETWORK
    ############################################################
    app_port: 8080
    route_host: "{{ app_name }}.apps.pgrhoso.dccloud.com"

  tasks:

    ############################################################
    # 1️⃣ PROCESS APACHE TEMPLATE
    ############################################################
    - name: Process Apache HTTPD template
      community.okd.openshift_process:
        name: "{{ template_name }}"
        namespace: "{{ template_namespace }}"
        namespace_target: "{{ runtime_namespace }}"
        parameters:
          NAME: "{{ app_name }}"
          NAMESPACE: "{{ template_namespace }}"
          HTTPD_VERSION: "{{ httpd_version }}"
          MEMORY_LIMIT: "{{ memory_limit }}"
          SOURCE_REPOSITORY_URL: "{{ git_repo_url }}"
      register: apache_template

    ############################################################
    # 2️⃣ APPLY GENERATED RESOURCES
    ############################################################
    - name: Create application resources
      community.okd.k8s:
        state: present
        namespace: "{{ runtime_namespace }}"
        definition: "{{ item }}"
      loop: "{{ apache_template.resources }}"

    ############################################################
    # 3️⃣ CREATE ROUTE (INGRESS)
    ############################################################
    - name: Create OpenShift Route
      community.okd.k8s:
        state: present
        namespace: "{{ runtime_namespace }}"
        definition:
          apiVersion: route.openshift.io/v1
          kind: Route
          metadata:
            name: "{{ app_name }}"
          spec:
            host: "{{ route_host }}"
            to:
              kind: Service
              name: "{{ app_name }}"
            port:
              targetPort: "{{ app_port }}"
            tls:
              termination: edge

    ############################################################
    # 4️⃣ NETWORK POLICY – SURVEY DRIVEN (FIXED INDENTATION)
    ############################################################
    - name: Apply NetworkPolicy (Survey Driven Ingress & Egress)
      community.okd.k8s:
        state: present
        namespace: "{{ runtime_namespace }}"
        definition:
          apiVersion: networking.k8s.io/v1
          kind: NetworkPolicy
          metadata:
            name: "{{ app_name }}-network-policy"
          spec:
            ####################################################
            # APPLY ONLY TO APPLICATION PODS
            ####################################################
            podSelector:
              matchLabels:
                name: "{{ app_name }}"

            policyTypes:
              - Ingress
              - Egress

            ####################################################
            # INGRESS – FROM SURVEY
            ####################################################
            ingress:
              - from:
{% for cidr in ingress_cidrs | from_yaml %}
                  - ipBlock:
                      cidr: {{ cidr }}
{% endfor %}
                ports:
{% for p in ingress_ports | from_yaml %}
                  - protocol: {{ p.protocol }}
                    port: {{ p.port }}
{% endfor %}

            ####################################################
            # EGRESS
            ####################################################
            egress:
              # DNS (MANDATORY)
              - to:
                  - namespaceSelector:
                      matchLabels:
                        kubernetes.io/metadata.name: openshift-dns
                ports:
                  - protocol: UDP
                    port: 53
                  - protocol: TCP
                    port: 53

              # FROM SURVEY
              - to:
{% for cidr in egress_cidrs | from_yaml %}
                  - ipBlock:
                      cidr: {{ cidr }}
{% endfor %}
                ports:
{% for p in egress_ports | from_yaml %}
                  - protocol: {{ p.protocol }}
                    port: {{ p.port }}
{% endfor %}

    ############################################################
    # 5️⃣ GUARANTEED NEW POD EVERY RUN
    ############################################################
    - name: Force rollout restart (always creates new pod)
      kubernetes.core.k8s:
        state: patched
        api_version: apps/v1
        kind: Deployment
        name: "{{ app_name }}"
        namespace: "{{ runtime_namespace }}"
        merge_type: strategic-merge
        definition:
          spec:
            template:
              metadata:
                annotations:
                  restartedAt: "{{ lookup('pipe', 'date +%s') }}"
