---
- name: Deploy Apache HTTP Server via AAP (Survey + Robust NetworkPolicy)
  hosts: localhost
  connection: local
  gather_facts: no

  vars:
    app_name: "{{ app_name }}"
    runtime_namespace: "{{ runtime_namespace }}"
    httpd_version: "{{ httpd_version }}"
    memory_limit: "{{ memory_limit }}"
    git_repo_url: "{{ git_repo_url }}"

    ingress_namespace: openshift-ingress
    ingress_ports: "{{ ingress_ports }}"     # TCP:8080
    egress_cidrs: "{{ egress_cidrs }}"       # 0.0.0.0/0 or GitHub CIDRs
    egress_ports: "{{ egress_ports }}"       # TCP:443

    template_name: httpd-example
    template_namespace: openshift
    app_port: 8080
    route_host: "{{ app_name }}.apps.pgrhoso.dccloud.com"

  tasks:

    ############################################################
    # PROCESS TEMPLATE
    ############################################################
    - name: Process Apache HTTPD template
      community.okd.openshift_process:
        name: "{{ template_name }}"
        namespace: "{{ template_namespace }}"
        namespace_target: "{{ runtime_namespace }}"
        parameters:
          NAME: "{{ app_name }}"
          NAMESPACE: "{{ template_namespace }}"
          HTTPD_VERSION: "{{ httpd_version }}"
          MEMORY_LIMIT: "{{ memory_limit }}"
          SOURCE_REPOSITORY_URL: "{{ git_repo_url }}"
      register: apache_template

    - name: Create application resources
      community.okd.k8s:
        state: present
        namespace: "{{ runtime_namespace }}"
        definition: "{{ item }}"
      loop: "{{ apache_template.resources }}"

    ############################################################
    # PARSE PORTS
    ############################################################
    - set_fact:
        ingress_ports_parsed: []
        egress_ports_parsed: []

    - name: Build ingress ports
      set_fact:
        ingress_ports_parsed: "{{ ingress_ports_parsed + [ {'protocol': item.split(':')[0] | upper, 'port': item.split(':')[1] | int } ] }}"
      loop: "{{ ingress_ports.split(',') | map('trim') | list }}"

    - name: Build egress ports
      set_fact:
        egress_ports_parsed: "{{ egress_ports_parsed + [ {'protocol': item.split(':')[0] | upper, 'port': item.split(':')[1] | int } ] }}"
      loop: "{{ egress_ports.split(',') | map('trim') | list }}"

    ############################################################
    # PARSE CIDRS
    ############################################################
    - set_fact:
        egress_to_blocks: []

    - name: Build egress CIDRs
      set_fact:
        egress_to_blocks: "{{ egress_to_blocks + [ {'ipBlock': {'cidr': item}} ] }}"
      loop: "{{ egress_cidrs.split(',') | map('trim') | list }}"

    ############################################################
    # APPLY NETWORK POLICY (FIXED)
    ############################################################
    - name: Apply NetworkPolicy
      community.okd.k8s:
        state: present
        namespace: "{{ runtime_namespace }}"
        definition:
          apiVersion: networking.k8s.io/v1
          kind: NetworkPolicy
          metadata:
            name: "{{ app_name }}-network-policy"
          spec:
            podSelector:
              matchLabels:
                name: "{{ app_name }}"

            policyTypes:
              - Ingress
              - Egress

            #####################
            # INGRESS (ROUTER)
            #####################
            ingress:
              - from:
                  - namespaceSelector:
                      matchLabels:
                        kubernetes.io/metadata.name: "{{ ingress_namespace }}"
                ports: "{{ ingress_ports_parsed }}"

            #####################
            # EGRESS
            #####################
            egress:
              # DNS (MANDATORY)
              - to:
                  - namespaceSelector:
                      matchLabels:
                        kubernetes.io/metadata.name: openshift-dns
                ports:
                  - protocol: UDP
                    port: 53
                  - protocol: TCP
                    port: 53

              # HTTPS / CIDR BASED
              - to: "{{ egress_to_blocks }}"
                ports: "{{ egress_ports_parsed }}"

    ############################################################
    # FORCE POD RESTART
    ############################################################
    - name: Force rollout restart
      kubernetes.core.k8s:
        state: patched
        api_version: apps/v1
        kind: Deployment
        name: "{{ app_name }}"
        namespace: "{{ runtime_namespace }}"
        merge_type: strategic-merge
        definition:
          spec:
            template:
              metadata:
                annotations:
                  restartedAt: "{{ lookup('pipe', 'date +%s') }}"
