---
- name: Deploy Apache HTTP Server (Catalog Template) via AAP
  hosts: localhost
  connection: local
  gather_facts: no

  vars:
    ############################################################
    # HARDCODED NETWORK VALUES
    ############################################################
    route_host: "httpd.apps.pgrhoso.dccloud.com"
    app_port: 8080
    ingress_namespace: "openshift-ingress"
    egress_cidr: "0.0.0.0/0"
    egress_port: 443

  tasks:
    ############################################################
    # Step 1: Process Apache HTTP Server template
    ############################################################
    - name: Process Apache HTTP Server template
      community.okd.openshift_process:
        name: httpd-example
        namespace: "{{ runtime_namespace }}"
        parameters:
          NAME: "{{ app_name }}"
          NAMESPACE: "{{ image_namespace }}"
          HTTPD_VERSION: "{{ httpd_version }}"
          MEMORY_LIMIT: "{{ memory_limit }}"
          SOURCE_REPOSITORY_URL: "{{ git_repo_url }}"
      register: apache_template

    ############################################################
    # Step 2: Create Deployment / Service / Pod
    ############################################################
    - name: Create Apache HTTP Server resources
      community.okd.k8s:
        state: present
        namespace: "{{ runtime_namespace }}"
        definition: "{{ item }}"
      loop: "{{ apache_template.resources }}"

    ############################################################
    # Step 3: Create Route (Ingress)
    ############################################################
    - name: Create Route
      community.okd.k8s:
        state: present
        namespace: "{{ runtime_namespace }}"
        definition:
          apiVersion: route.openshift.io/v1
          kind: Route
          metadata:
            name: "{{ app_name }}"
          spec:
            host: "{{ route_host }}"
            to:
              kind: Service
              name: "{{ app_name }}"
            port:
              targetPort: "{{ app_port }}"
            tls:
              termination: edge

    ############################################################
    # Step 4: NetworkPolicy (Ingress + Egress)
    ############################################################
    - name: Apply NetworkPolicy
      community.okd.k8s:
        state: present
        namespace: "{{ runtime_namespace }}"
        definition:
          apiVersion: networking.k8s.io/v1
          kind: NetworkPolicy
          metadata:
            name: "{{ app_name }}-network-policy"
          spec:
            podSelector:
              matchLabels:
                app: "{{ app_name }}"
            policyTypes:
              - Ingress
              - Egress

            ingress:
              - from:
                  - namespaceSelector:
                      matchLabels:
                        kubernetes.io/metadata.name: "{{ ingress_namespace }}"
                ports:
                  - protocol: TCP
                    port: "{{ app_port }}"

            egress:
              - to:
                  - ipBlock:
                      cidr: "{{ egress_cidr }}"
                ports:
                  - protocol: TCP
                    port: "{{ egress_port }}"
