---
- name: Deploy Apache HTTPD on OpenShift using AAP
  hosts: localhost
  connection: local
  gather_facts: no

  vars:
    template_name: httpd-example
    template_namespace: "{{ image_namespace }}"

  tasks:

    ##########################################################################
    # 1️⃣ Extract API server + token from the kubeconfig provided by AAP
    ##########################################################################
    - name: Read kubeconfig
      slurp:
        src: "~/.kube/config"
      register: kube_raw

    - name: Parse kubeconfig
      set_fact:
        kubeconfig: "{{ kube_raw.content | b64decode | from_yaml }}"

    - name: Extract cluster server URL
      set_fact:
        api_server: "{{ kubeconfig.clusters[0].cluster.server }}"

    - name: Extract Bearer token
      set_fact:
        bearer_token: "{{ kubeconfig.users[0].user.token }}"

    ##########################################################################
    # 2️⃣ Process OpenShift Template using processedtemplates API
    ##########################################################################
    - name: Process OpenShift Template
      uri:
        url: "{{ api_server }}/apis/template.openshift.io/v1/namespaces/{{ template_namespace }}/processedtemplates"
        method: POST
        headers:
          Authorization: "Bearer {{ bearer_token }}"
          Accept: "application/json"
          Content-Type: "application/json"
        body_format: json
        body:
          apiVersion: template.openshift.io/v1
          kind: Template
          metadata:
            name: "{{ template_name }}"
          parameters:
            - { name: NAME, value: "{{ app_name }}" }
            - { name: NAMESPACE, value: "{{ runtime_namespace }}" }
            - { name: HTTPD_VERSION, value: "{{ httpd_version }}" }
            - { name: MEMORY_LIMIT, value: "{{ memory_limit }}" }
            - { name: SOURCE_REPOSITORY_URL, value: "{{ git_repo_url }}" }
        validate_certs: false
      register: processed

    ##########################################################################
    # 3️⃣ Extract objects
    ##########################################################################
    - name: Extract processed objects
      set_fact:
        apache_objects: "{{ processed.json.objects }}"

    ##########################################################################
    # 4️⃣ Apply objects
    ##########################################################################
    - name: Apply template resources
      kubernetes.core.k8s:
        state: present
        namespace: "{{ runtime_namespace }}"
        definition: "{{ item }}"
      loop: "{{ apache_objects }}"

    ##########################################################################
    # 5️⃣ NETWORK POLICY BUILDING (your survey fields)
    ##########################################################################

    - name: Init port lists
      set_fact:
        ingress_ports_parsed: []
        egress_ports_parsed: []

    - name: Build ingress ports
      set_fact:
        ingress_ports_parsed: "{{ ingress_ports_parsed +
          [ {'protocol': item.split(':')[0] | upper,
             'port': item.split(':')[1] | int } ] }}"
      loop: "{{ ingress_ports.split(',') | map('trim') | list }}"

    - name: Build egress ports
      set_fact:
        egress_ports_parsed: "{{ egress_ports_parsed +
          [ {'protocol': item.split(':')[0] | upper,
             'port': item.split(':')[1] | int } ] }}"
      loop: "{{ egress_ports.split(',') | map('trim') | list }}"

    - name: Init CIDR lists
      set_fact:
        ingress_from_blocks: []
        egress_to_blocks: []

    - name: Build ingress CIDRs
      set_fact:
        ingress_from_blocks: "{{ ingress_from_blocks + [ {'ipBlock': {'cidr': item}} ] }}"
      loop: "{{ ingress_cidrs.split(',') | map('trim') | list }}"

    - name: Build egress CIDRs
      set_fact:
        egress_to_blocks: "{{ egress_to_blocks + [ {'ipBlock': {'cidr': item}} ] }}"
      loop: "{{ egress_cidrs.split(',') | map('trim') | list }}"

    ##########################################################################
    # 6️⃣ Apply NetworkPolicy
    ##########################################################################
    - name: Apply NetworkPolicy
      kubernetes.core.k8s:
        state: present
        namespace: "{{ runtime_namespace }}"
        definition:
          apiVersion: networking.k8s.io/v1
          kind: NetworkPolicy
          metadata:
            name: "{{ app_name }}-network-policy"
          spec:
            podSelector:
              matchLabels:
                name: "{{ app_name }}"
            policyTypes: [Ingress, Egress]
            ingress:
              - from: "{{ ingress_from_blocks }}"
                ports: "{{ ingress_ports_parsed }}"
            egress:
              - to:
                  - ipBlock: { cidr: "{{ dns_service_cidr }}" }
                ports:
                  - { protocol: UDP, port: 53 }
                  - { protocol: TCP, port: 53 }
              - to:
                  - ipBlock: { cidr: "{{ dns_local_ip }}" }
                ports:
                  - { protocol: UDP, port: 53 }
                  - { protocol: TCP, port: 53 }
              - to: "{{ egress_to_blocks }}"
                ports: "{{ egress_ports_parsed }}"

    ##########################################################################
    # 7️⃣ Force pod restart
    ##########################################################################
    - name: Restart Deployment
      kubernetes.core.k8s:
        state: patched
        api_version: apps/v1
        kind: Deployment
        name: "{{ app_name }}"
        namespace: "{{ runtime_namespace }}"
        merge_type: strategic-merge
        definition:
          spec:
            template:
              metadata:
                annotations:
                  restartedAt: "{{ lookup('pipe', 'date +%s') }}"
