---
- name: Deploy Apache HTTP Server via AAP (Survey + Strict NetworkPolicy)
  hosts: localhost
  connection: local
  gather_facts: no

  vars:
    app_name: "{{ app_name }}"
    runtime_namespace: "{{ runtime_namespace }}"
    httpd_version: "{{ httpd_version }}"
    memory_limit: "{{ memory_limit }}"
    git_repo_url: "{{ git_repo_url }}"

    # Survey CSV inputs
    ingress_ports: "{{ ingress_ports }}"
    ingress_cidrs: "{{ ingress_cidrs }}"
    egress_cidrs: "{{ egress_cidrs }}"
    egress_ports: "{{ egress_ports }}"

    # DNS defaults
    dns_service_cidr: "{{ dns_service_cidr | default('172.30.0.0/16') }}"
    dns_node_local_ip: "{{ dns_node_local_ip | default('169.254.0.5/32') }}"

    # Template constants
    template_name: httpd-example
    template_namespace: openshift
    app_port: 8080
    route_host: "{{ app_name }}.apps.pgrhoso.dccloud.com"

  tasks:

    ############################################################
    # 1️⃣ PROCESS TEMPLATE USING k8s_raw
    ############################################################
    - name: Load OpenShift template
      kubernetes.core.k8s_info:
        api_version: template.openshift.io/v1
        kind: Template
        name: "{{ template_name }}"
        namespace: "{{ template_namespace }}"
      register: tmpl

    - name: Process template into objects
      kubernetes.core.k8s_raw:
        state: processed
        resource_definition: "{{ tmpl.resources[0] }}"
        namespace: "{{ runtime_namespace }}"
        template_parameters:
          NAME: "{{ app_name }}"
          NAMESPACE: "{{ template_namespace }}"
          HTTPD_VERSION: "{{ httpd_version }}"
          MEMORY_LIMIT: "{{ memory_limit }}"
          SOURCE_REPOSITORY_URL: "{{ git_repo_url }}"
      register: apache_template

    ############################################################
    # 2️⃣ APPLY GENERATED RESOURCES
    ############################################################
    - name: Apply resources from processed template
      kubernetes.core.k8s:
        state: present
        namespace: "{{ runtime_namespace }}"
        definition: "{{ item }}"
      loop: "{{ apache_template['result']['items'] }}"

    ############################################################
    # 3️⃣ PARSE PORTS
    ############################################################
    - set_fact:
        ingress_ports_parsed: []
        egress_ports_parsed: []

    - name: Parse ingress ports
      set_fact:
        ingress_ports_parsed: "{{ ingress_ports_parsed + [ {'protocol': item.split(':')[0] | upper, 'port': item.split(':')[1] | int } ] }}"
      loop: "{{ ingress_ports.split(',') | map('trim') }}"

    - name: Parse egress ports
      set_fact:
        egress_ports_parsed: "{{ egress_ports_parsed + [ {'protocol': item.split(':')[0] | upper, 'port': item.split(':')[1] | int } ] }}"
      loop: "{{ egress_ports.split(',') | map('trim') }}"

    ############################################################
    # 4️⃣ PARSE CIDRs
    ############################################################
    - set_fact:
        ingress_from_blocks: []
        egress_to_blocks: []

    - name: Parse ingress CIDRs
      set_fact:
        ingress_from_blocks: "{{ ingress_from_blocks + [ {'ipBlock': {'cidr': item}} ] }}"
      loop: "{{ ingress_cidrs.split(',') | map('trim') }}"

    - name: Parse egress CIDRs
      set_fact:
        egress_to_blocks: "{{ egress_to_blocks + [ {'ipBlock': {'cidr': item}} ] }}"
      loop: "{{ egress_cidrs.split(',') | map('trim') }}"

    ############################################################
    # 5️⃣ APPLY NETWORK POLICY
    ############################################################
    - name: Apply NetworkPolicy
      kubernetes.core.k8s:
        state: present
        namespace: "{{ runtime_namespace }}"
        definition:
          apiVersion: networking.k8s.io/v1
          kind: NetworkPolicy
          metadata:
            name: "{{ app_name }}-network-policy"
          spec:
            podSelector:
              matchLabels:
                name: "{{ app_name }}"
            policyTypes:
              - Ingress
              - Egress

            ingress:
              - from: "{{ ingress_from_blocks }}"
                ports: "{{ ingress_ports_parsed }}"

            egress:
              - to:
                  - ipBlock:
                      cidr: "{{ dns_service_cidr }}"
                ports:
                  - protocol: UDP
                    port: 53
                  - protocol: TCP
                    port: 53
              - to:
                  - ipBlock:
                      cidr: "{{ dns_node_local_ip }}"
                ports:
                  - protocol: UDP
                    port: 53
                  - protocol: TCP
                    port: 53
              - to: "{{ egress_to_blocks }}"
                ports: "{{ egress_ports_parsed }}"

    ############################################################
    # 6️⃣ FORCE POD RESTART
    ############################################################
    - name: Force Deployment Restart (New Pod Every Run)
      kubernetes.core.k8s:
        state: patched
        api_version: apps/v1
        kind: Deployment
        name: "{{ app_name }}"
        namespace: "{{ runtime_namespace }}"
        merge_type: strategic-merge
        definition:
          spec:
            template:
              metadata:
                annotations:
                  restartedAt: "{{ lookup('pipe', 'date +%s%N') }}"
