---
- name: Deploy Apache HTTP Server via AAP (Generic & Secure)
  hosts: localhost
  connection: local
  gather_facts: no

  vars:
    # -------------------------------
    # Network / Route configuration
    # -------------------------------
    route_host: "{{ app_name }}.apps.pgrhoso.dccloud.com"
    app_port: 8080
    ingress_namespace: openshift-ingress

  tasks:
    ############################################################
    # 1️⃣ Process OpenShift Template (GENERIC)
    ############################################################
    - name: Process Apache HTTPD template
      community.okd.openshift_process:
        name: "{{ app_name }}"
        namespace: "{{ image_namespace }}"          # where template exists
        namespace_target: "{{ runtime_namespace }}" # where app is created
        parameters:
          NAME: "{{ app_name }}"
          NAMESPACE: "{{ image_namespace }}"
          HTTPD_VERSION: "{{ httpd_version }}"
          MEMORY_LIMIT: "{{ memory_limit }}"
          SOURCE_REPOSITORY_URL: "{{ git_repo_url }}"
      register: apache_template

    ############################################################
    # 2️⃣ Create all generated resources
    ############################################################
    - name: Apply generated OpenShift resources
      community.okd.k8s:
        state: present
        namespace: "{{ runtime_namespace }}"
        definition: "{{ item }}"
      loop: "{{ apache_template.resources }}"

    ############################################################
    # 3️⃣ Create Route (Ingress)
    ############################################################
    - name: Create OpenShift Route
      community.okd.k8s:
        state: present
        namespace: "{{ runtime_namespace }}"
        definition:
          apiVersion: route.openshift.io/v1
          kind: Route
          metadata:
            name: "{{ app_name }}"
          spec:
            host: "{{ route_host }}"
            to:
              kind: Service
              name: "{{ app_name }}"
            port:
              targetPort: "{{ app_port }}"
            tls:
              termination: edge

    ############################################################
    # 4️⃣ NetworkPolicy – DEFAULT DENY (INGRESS + EGRESS)
    ############################################################
    - name: Apply default deny NetworkPolicy (label independent)
      community.okd.k8s:
        state: present
        namespace: "{{ runtime_namespace }}"
        definition:
          apiVersion: networking.k8s.io/v1
          kind: NetworkPolicy
          metadata:
            name: "{{ app_name }}-default-deny"
          spec:
            podSelector: {}     # 🔑 applies to ALL pods
            policyTypes:
              - Ingress
              - Egress

            # ✅ Allow ingress ONLY from OpenShift router
            ingress:
              - from:
                  - namespaceSelector:
                      matchLabels:
                        kubernetes.io/metadata.name: "{{ ingress_namespace }}"
                ports:
                  - protocol: TCP
                    port: "{{ app_port }}"

            # ❌ BLOCK ALL EGRESS
            egress: []
