---
- name: Deploy Apache HTTP Server via AAP (Survey + Strict NetworkPolicy)
  hosts: localhost
  connection: local
  gather_facts: no

  ############################################################
  # SURVEY VARIABLES (PLAIN STRINGS)
  ############################################################
  vars:
    app_name: "{{ app_name }}"
    runtime_namespace: "{{ runtime_namespace }}"
    httpd_version: "{{ httpd_version }}"
    memory_limit: "{{ memory_limit }}"
    git_repo_url: "{{ git_repo_url }}"

    # Survey-driven inputs (CSV / single-line)
    ingress_ports: "{{ ingress_ports }}"          # TCP:8080
    ingress_cidrs: "{{ ingress_cidrs }}"          # 0.0.0.0/0 or 10.68.0.0/16
    egress_cidrs: "{{ egress_cidrs }}"            # allowed external CIDRs
    egress_ports: "{{ egress_ports }}"            # TCP:443

    # DNS (OpenShift defaults)
    dns_service_cidr: "{{ dns_service_cidr | default('172.30.0.0/16') }}"
    dns_node_local_ip: "{{ dns_node_local_ip | default('169.254.0.5/32') }}"

    # Fixed OpenShift values
    template_name: httpd-example
    template_namespace: openshift
    app_port: 8080

  ############################################################
  # TASKS
  ############################################################
  tasks:

    ############################################################
    # 1️⃣ PROCESS APACHE HTTPD TEMPLATE
    ############################################################
    - name: Process Apache HTTPD template
      community.okd.openshift_process:
        name: "{{ template_name }}"
        namespace: "{{ template_namespace }}"
        namespace_target: "{{ runtime_namespace }}"
        parameters:
          NAME: "{{ app_name }}"
          NAMESPACE: "{{ runtime_namespace }}"
          HTTPD_VERSION: "{{ httpd_version }}"
          MEMORY_LIMIT: "{{ memory_limit }}"
          SOURCE_REPOSITORY_URL: "{{ git_repo_url }}"
      register: apache_template

    ############################################################
    # 2️⃣ APPLY GENERATED RESOURCES
    ############################################################
    - name: Create application resources
      community.okd.k8s:
        state: present
        namespace: "{{ runtime_namespace }}"
        definition: "{{ item }}"
      loop: "{{ apache_template.resources }}"

    ############################################################
    # 3️⃣ PARSE SURVEY PORTS
    ############################################################
    - name: Initialize parsed port lists
      set_fact:
        ingress_ports_parsed: []
        egress_ports_parsed: []

    - name: Build ingress ports
      set_fact:
        ingress_ports_parsed: >-
          {{ ingress_ports_parsed +
             [ {'protocol': item.split(':')[0] | upper,
                'port': item.split(':')[1] | int } ] }}
      loop: "{{ ingress_ports.split(',') | map('trim') | list }}"

    - name: Build egress ports
      set_fact:
        egress_ports_parsed: >-
          {{ egress_ports_parsed +
             [ {'protocol': item.split(':')[0] | upper,
                'port': item.split(':')[1] | int } ] }}
      loop: "{{ egress_ports.split(',') | map('trim') | list }}"

    ############################################################
    # 4️⃣ PARSE CIDRs
    ############################################################
    - name: Initialize CIDR lists
      set_fact:
        ingress_from_blocks: []
        egress_to_blocks: []

    - name: Build ingress CIDRs
      set_fact:
        ingress_from_blocks: >-
          {{ ingress_from_blocks +
             [ {'ipBlock': {'cidr': item}} ] }}
      loop: "{{ ingress_cidrs.split(',') | map('trim') | list }}"

    - name: Build egress CIDRs
      set_fact:
        egress_to_blocks: >-
          {{ egress_to_blocks +
             [ {'ipBlock': {'cidr': item}} ] }}
      loop: "{{ egress_cidrs.split(',') | map('trim') | list }}"

    ############################################################
    # 5️⃣ APPLY STRICT NETWORK POLICY
    ############################################################
    - name: Apply NetworkPolicy
      community.okd.k8s:
        state: present
        namespace: "{{ runtime_namespace }}"
        definition:
          apiVersion: networking.k8s.io/v1
          kind: NetworkPolicy
          metadata:
            name: "{{ app_name }}-network-policy"
          spec:
            podSelector:
              matchLabels:
                deployment: "{{ app_name }}"

            policyTypes:
              - Ingress
              - Egress

            # ---------- INGRESS ----------
            ingress:
              - from: "{{ ingress_from_blocks }}"
                ports: "{{ ingress_ports_parsed }}"

            # ---------- EGRESS ----------
            egress:
              # DNS via service network
              - to:
                  - ipBlock:
                      cidr: "{{ dns_service_cidr }}"
                ports:
                  - protocol: UDP
                    port: 53
                  - protocol: TCP
                    port: 53

              # DNS via node-local cache
              - to:
                  - ipBlock:
                      cidr: "{{ dns_node_local_ip }}"
                ports:
                  - protocol: UDP
                    port: 53
                  - protocol: TCP
                    port: 53

              # Explicitly allowed external CIDRs
              - to: "{{ egress_to_blocks }}"
                ports: "{{ egress_ports_parsed }}"

    ############################################################
    # 6️⃣ FORCE POD ROLLOUT (APPLY POLICY IMMEDIATELY)
    ############################################################
    - name: Force deployment rollout
      kubernetes.core.k8s:
        state: patched
        api_version: apps/v1
        kind: Deployment
        name: "{{ app_name }}"
        namespace: "{{ runtime_namespace }}"
        merge_type: strategic-merge
        definition:
          spec:
            template:
              metadata:
                annotations:
                  restartedAt: "{{ lookup('pipe', 'date +%s') }}"
