---
- name: Deploy Apache HTTP Server via AAP (Survey + Strict NetworkPolicy)
  hosts: localhost
  connection: local
  gather_facts: no

  vars:
    template_name: httpd-example
    template_namespace: "{{ image_namespace }}"

  tasks:

    ##########################################################################
    # 1️⃣ Create authenticated Kubernetes/OpenShift API client
    ##########################################################################
    - name: Load k8s client
      kubernetes.core.k8s_client:
      register: k8sapi

    ##########################################################################
    # 2️⃣ PROCESS TEMPLATE VIA /processedtemplates ENDPOINT
    ##########################################################################
    - name: Process OpenShift Template via API
      uri:
        url: "{{ k8sapi.config.host }}/apis/template.openshift.io/v1/namespaces/{{ template_namespace }}/processedtemplates"
        method: POST
        headers:
          Authorization: "Bearer {{ k8sapi.config.api_key['authorization'] }}"
          Accept: "application/json"
          Content-Type: "application/json"
        body_format: json
        body:
          kind: Template
          apiVersion: template.openshift.io/v1
          metadata:
            name: "{{ template_name }}"
          parameters:
            - name: NAME
              value: "{{ app_name }}"
            - name: NAMESPACE
              value: "{{ runtime_namespace }}"
            - name: HTTPD_VERSION
              value: "{{ httpd_version }}"
            - name: MEMORY_LIMIT
              value: "{{ memory_limit }}"
            - name: SOURCE_REPOSITORY_URL
              value: "{{ git_repo_url }}"
        validate_certs: false
      register: processed

    ##########################################################################
    # 3️⃣ EXTRACT PROCESSED OBJECTS
    ##########################################################################
    - name: Extract Processed Objects
      set_fact:
        apache_objects: "{{ processed.json.objects }}"

    ##########################################################################
    # 4️⃣ APPLY THE GENERATED RESOURCES
    ##########################################################################
    - name: Apply Apache Template Objects
      kubernetes.core.k8s:
        state: present
        namespace: "{{ runtime_namespace }}"
        definition: "{{ item }}"
      loop: "{{ apache_objects }}"

    ##########################################################################
    # 5️⃣ Now apply NetworkPolicy (Survey-controlled ports + CIDRs)
    ##########################################################################

    - name: Initialize port lists
      set_fact:
        ingress_ports_parsed: []
        egress_ports_parsed: []

    - name: Build ingress ports list
      set_fact:
        ingress_ports_parsed: "{{ ingress_ports_parsed +
          [ {'protocol': item.split(':')[0] | upper, 'port': item.split(':')[1] | int } ] }}"
      loop: "{{ ingress_ports.split(',') | map('trim') | list }}"

    - name: Build egress ports list
      set_fact:
        egress_ports_parsed: "{{ egress_ports_parsed +
          [ {'protocol': item.split(':')[0] | upper, 'port': item.split(':')[1] | int } ] }}"
      loop: "{{ egress_ports.split(',') | map('trim') | list }}"

    ##########################################################################
    # CIDRs (Ingress + Egress)
    ##########################################################################
    - name: Initialize CIDR lists
      set_fact:
        ingress_from_blocks: []
        egress_to_blocks: []

    - name: Build ingress CIDRs
      set_fact:
        ingress_from_blocks: "{{ ingress_from_blocks + [ {'ipBlock': {'cidr': item}} ] }}"
      loop: "{{ ingress_cidrs.split(',') | map('trim') | list }}"

    - name: Build egress CIDRs
      set_fact:
        egress_to_blocks: "{{ egress_to_blocks + [ {'ipBlock': {'cidr': item}} ] }}"
      loop: "{{ egress_cidrs.split(',') | map('trim') | list }}"

    ##########################################################################
    # 6️⃣ Apply NetworkPolicy
    ##########################################################################
    - name: Apply NetworkPolicy
      kubernetes.core.k8s:
        state: present
        namespace: "{{ runtime_namespace }}"
        definition:
          apiVersion: networking.k8s.io/v1
          kind: NetworkPolicy
          metadata:
            name: "{{ app_name }}-network-policy"
          spec:
            podSelector:
              matchLabels:
                name: "{{ app_name }}"
            policyTypes:
              - Ingress
              - Egress

            ingress:
              - from: "{{ ingress_from_blocks }}"
                ports: "{{ ingress_ports_parsed }}"

            egress:
              # DNS service CIDR
              - to:
                  - ipBlock:
                      cidr: "{{ dns_service_cidr }}"
                ports:
                  - { protocol: UDP, port: 53 }
                  - { protocol: TCP, port: 53 }

              # Node local DNS IP
              - to:
                  - ipBlock:
                      cidr: "{{ dns_local_ip }}"
                ports:
                  - { protocol: UDP, port: 53 }
                  - { protocol: TCP, port: 53 }

              # Allowed external CIDRs
              - to: "{{ egress_to_blocks }}"
                ports: "{{ egress_ports_parsed }}"

    ##########################################################################
    # 7️⃣ Restart Deployment to apply NetworkPolicy
    ##########################################################################
    - name: Force rollout restart
      kubernetes.core.k8s:
        state: patched
        api_version: apps/v1
        kind: Deployment
        name: "{{ app_name }}"
        namespace: "{{ runtime_namespace }}"
        merge_type: strategic-merge
        definition:
          spec:
            template:
              metadata:
                annotations:
                  restartedAt: "{{ lookup('pipe', 'date +%s') }}"
