---
- name: Deploy Apache HTTP Server via AAP (Ingress OK, Internet Restricted)
  hosts: localhost
  connection: local
  gather_facts: no

  vars:
    ############################################################
    # OPENSHIFT TEMPLATE DETAILS
    ############################################################
    template_name: httpd-example
    template_namespace: openshift

    ############################################################
    # SURVEY VARIABLES
    ############################################################
    app_name: "{{ app_name }}"
    runtime_namespace: "{{ runtime_namespace }}"
    httpd_version: "{{ httpd_version }}"
    memory_limit: "{{ memory_limit }}"
    git_repo_url: "{{ git_repo_url }}"

    ############################################################
    # NETWORK
    ############################################################
    app_port: 8080
    ingress_namespace: openshift-ingress
    route_host: "{{ app_name }}.apps.pgrhoso.dccloud.com"

  tasks:

    ############################################################
    # 1️⃣ PROCESS APACHE TEMPLATE
    ############################################################
    - name: Process Apache HTTPD template
      community.okd.openshift_process:
        name: "{{ template_name }}"
        namespace: "{{ template_namespace }}"
        namespace_target: "{{ runtime_namespace }}"
        parameters:
          NAME: "{{ app_name }}"
          NAMESPACE: "{{ template_namespace }}"
          HTTPD_VERSION: "{{ httpd_version }}"
          MEMORY_LIMIT: "{{ memory_limit }}"
          SOURCE_REPOSITORY_URL: "{{ git_repo_url }}"
      register: apache_template

    ############################################################
    # 2️⃣ APPLY GENERATED RESOURCES
    ############################################################
    - name: Create application resources
      community.okd.k8s:
        state: present
        namespace: "{{ runtime_namespace }}"
        definition: "{{ item }}"
      loop: "{{ apache_template.resources }}"

    ############################################################
    # 3️⃣ CREATE ROUTE (INGRESS)
    ############################################################
    - name: Create OpenShift Route
      community.okd.k8s:
        state: present
        namespace: "{{ runtime_namespace }}"
        definition:
          apiVersion: route.openshift.io/v1
          kind: Route
          metadata:
            name: "{{ app_name }}"
          spec:
            host: "{{ route_host }}"
            to:
              kind: Service
              name: "{{ app_name }}"
            port:
              targetPort: "{{ app_port }}"
            tls:
              termination: edge

    ############################################################
    # 4️⃣ NETWORK POLICY – CORRECT & SECURE
    ############################################################
    - name: Apply NetworkPolicy (DNS + GitHub ONLY)
      community.okd.k8s:
        state: present
        namespace: "{{ runtime_namespace }}"
        definition:
          apiVersion: networking.k8s.io/v1
          kind: NetworkPolicy
          metadata:
            name: "{{ app_name }}-restricted-egress"
          spec:
            podSelector:
              matchLabels:
                name: "{{ app_name }}"

            policyTypes:
              - Ingress
              - Egress

            ####################################################
            # INGRESS – OpenShift Router ONLY
            ####################################################
            ingress:
              - from:
                  - namespaceSelector:
                      matchLabels:
                        kubernetes.io/metadata.name: "{{ ingress_namespace }}"
                ports:
                  - protocol: TCP
                    port: "{{ app_port }}"

            ####################################################
            # EGRESS – DNS + GITHUB ONLY
            ####################################################
            egress:
              # DNS
              - to:
                  - ipBlock:
                      cidr: 0.0.0.0/0
                ports:
                  - protocol: UDP
                    port: 53
                  - protocol: TCP
                    port: 53

              # GitHub ONLY (no Google, no internet)
              - to:
                  - ipBlock:
                      cidr: 140.82.0.0/16
                  - ipBlock:
                      cidr: 192.30.252.0/22
                  - ipBlock:
                      cidr: 185.199.108.0/22
                ports:
                  - protocol: TCP
                    port: 443

    ############################################################
    # 5️⃣ SCALE DEPLOYMENT → NEW POD CREATED
    ############################################################
    - name: Scale deployment to create NEW pod
      kubernetes.core.k8s:
        state: patched
        api_version: apps/v1
        kind: Deployment
        name: "{{ app_name }}"
        namespace: "{{ runtime_namespace }}"
        merge_type: strategic-merge
        definition:
          spec:
            replicas: 0
