---
- name: Deploy Apache HTTP Server via AAP (Survey + Strict NetworkPolicy)
  hosts: localhost
  connection: local
  gather_facts: no

  vars:
    app_name: "{{ app_name }}"
    runtime_namespace: "{{ runtime_namespace }}"
    httpd_version: "{{ httpd_version }}"
    memory_limit: "{{ memory_limit }}"
    git_repo_url: "{{ git_repo_url }}"

    ingress_ports: "{{ ingress_ports }}"
    ingress_cidrs: "{{ ingress_cidrs }}"
    egress_cidrs: "{{ egress_cidrs }}"
    egress_ports: "{{ egress_ports }}"

    dns_service_cidr: "{{ dns_service_cidr | default('172.30.0.0/16') }}"
    dns_node_local_ip: "{{ dns_node_local_ip | default('169.254.0.5/32') }}"

    template_name: httpd-example
    template_namespace: openshift

  tasks:

    #################################################################
    # 1️⃣ CALL OPENSHIFT TEMPLATE PROCESSOR API
    #################################################################
    - name: Process template using Template Processor API
      kubernetes.core.k8s:
        api_version: template.openshift.io/v1
        kind: Template
        namespace: "{{ template_namespace }}"
        name: "{{ template_name }}"
        state: present
        apply: false
        wait: false
        definition:
          apiVersion: template.openshift.io/v1
          kind: Template
          metadata:
            name: "{{ template_name }}"
            namespace: "{{ template_namespace }}"
          parameters:
            - name: NAME
              value: "{{ app_name }}"
            - name: NAMESPACE
              value: "{{ runtime_namespace }}"
            - name: HTTPD_VERSION
              value: "{{ httpd_version }}"
            - name: MEMORY_LIMIT
              value: "{{ memory_limit }}"
            - name: SOURCE_REPOSITORY_URL
              value: "{{ git_repo_url }}"
      register: processed

    #################################################################
    # 2️⃣ EXTRACT GENERATED OBJECTS
    #################################################################
    - name: Extract objects from processed template
      set_fact:
        apache_objects: "{{ processed.result.objects }}"

    #################################################################
    # 3️⃣ APPLY GENERATED OBJECTS
    #################################################################
    - name: Apply Apache objects
      kubernetes.core.k8s:
        state: present
        namespace: "{{ runtime_namespace }}"
        definition: "{{ item }}"
      loop: "{{ apache_objects }}"

    #################################################################
    # 4️⃣ REST OF YOUR LOGIC (NETWORKPOLICY)
    #################################################################

    - name: Init parsed port lists
      set_fact:
        ingress_ports_parsed: []
        egress_ports_parsed: []

    - name: Build ingress ports
      set_fact:
        ingress_ports_parsed: >-
          {{ ingress_ports_parsed +
             [ {'protocol': item.split(':')[0] | upper,
                'port': item.split(':')[1] | int } ] }}
      loop: "{{ ingress_ports.split(',') | map('trim') | list }}"

    - name: Build egress ports
      set_fact:
        egress_ports_parsed: >-
          {{ egress_ports_parsed +
             [ {'protocol': item.split(':')[0] | upper,
                'port': item.split(':')[1] | int } ] }}
      loop: "{{ egress_ports.split(',') | map('trim') | list }}"

    - name: Init CIDR lists
      set_fact:
        ingress_from_blocks: []
        egress_to_blocks: []

    - name: Build ingress CIDRs
      set_fact:
        ingress_from_blocks: "{{ ingress_from_blocks + [ {'ipBlock': {'cidr': item}} ] }}"
      loop: "{{ ingress_cidrs.split(',') | map('trim') | list }}"

    - name: Build egress CIDRs
      set_fact:
        egress_to_blocks: "{{ egress_to_blocks + [ {'ipBlock': {'cidr': item}} ] }}"
      loop: "{{ egress_cidrs.split(',') | map('trim') | list }}"

    - name: Apply NetworkPolicy
      kubernetes.core.k8s:
        state: present
        namespace: "{{ runtime_namespace }}"
        definition:
          apiVersion: networking.k8s.io/v1
          kind: NetworkPolicy
          metadata:
            name: "{{ app_name }}-network-policy"
          spec:
            podSelector:
              matchLabels:
                name: "{{ app_name }}"
            policyTypes: [Ingress, Egress]
            ingress:
              - from: "{{ ingress_from_blocks }}"
                ports: "{{ ingress_ports_parsed }}"
            egress:
              - to:
                  - ipBlock: { cidr: "{{ dns_service_cidr }}" }
                ports:
                  - protocol: UDP
                    port: 53
                  - protocol: TCP
                    port: 53
              - to:
                  - ipBlock: { cidr: "{{ dns_node_local_ip }}" }
                ports:
                  - protocol: UDP
                    port: 53
                  - protocol: TCP
                    port: 53
              - to: "{{ egress_to_blocks }}"
                ports: "{{ egress_ports_parsed }}"

    - name: Force rollout restart
      kubernetes.core.k8s:
        state: patched
        api_version: apps/v1
        kind: Deployment
        name: "{{ app_name }}"
        namespace: "{{ runtime_namespace }}"
        merge_type: strategic-merge
        definition:
          spec:
            template:
              metadata:
                annotations:
                  restartedAt: "{{ lookup('pipe', 'date +%s') }}"
