---
- name: Deploy Apache HTTP Server via AAP (Ingress Allowed, Internet Blocked)
  hosts: localhost
  connection: local
  gather_facts: no

  ############################################################
  # VARIABLES (FROM SURVEY)
  ############################################################
  vars:
    # OpenShift template info (FIXED)
    template_name: httpd-example
    template_namespace: openshift

    # Application inputs
    app_name: "{{ app_name }}"
    runtime_namespace: "{{ runtime_namespace }}"
    httpd_version: "{{ httpd_version }}"
    memory_limit: "{{ memory_limit }}"
    git_repo_url: "{{ git_repo_url }}"

    # Networking
    app_port: 8080
    ingress_namespace: openshift-ingress
    route_host: "{{ app_name }}.apps.pgrhoso.dccloud.com"

  tasks:

    ############################################################
    # 1️⃣ Process Apache HTTPD OpenShift Template
    ############################################################
    - name: Process Apache HTTPD template
      community.okd.openshift_process:
        name: "{{ template_name }}"
        namespace: "{{ template_namespace }}"
        namespace_target: "{{ runtime_namespace }}"
        parameters:
          NAME: "{{ app_name }}"
          NAMESPACE: "{{ template_namespace }}"
          HTTPD_VERSION: "{{ httpd_version }}"
          MEMORY_LIMIT: "{{ memory_limit }}"
          SOURCE_REPOSITORY_URL: "{{ git_repo_url }}"
      register: apache_template

    ############################################################
    # 2️⃣ Apply Generated Resources
    ############################################################
    - name: Create application resources
      community.okd.k8s:
        state: present
        namespace: "{{ runtime_namespace }}"
        definition: "{{ item }}"
      loop: "{{ apache_template.resources }}"

    ############################################################
    # 3️⃣ Create Route (Ingress)
    ############################################################
    - name: Create OpenShift Route
      community.okd.k8s:
        state: present
        namespace: "{{ runtime_namespace }}"
        definition:
          apiVersion: route.openshift.io/v1
          kind: Route
          metadata:
            name: "{{ app_name }}"
          spec:
            host: "{{ route_host }}"
            to:
              kind: Service
              name: "{{ app_name }}"
            port:
              targetPort: "{{ app_port }}"
            tls:
              termination: edge

    ############################################################
    # 4️⃣ NetworkPolicy – ALL PODS, INTERNET BLOCKED
    ############################################################
    - name: Apply NetworkPolicy (Block Internet, Allow Internal)
      community.okd.k8s:
        state: present
        namespace: "{{ runtime_namespace }}"
        definition:
          apiVersion: networking.k8s.io/v1
          kind: NetworkPolicy
          metadata:
            name: deny-internet-allow-internal
          spec:
            podSelector: {}   # ✅ applies to ALL pods
            policyTypes:
              - Ingress
              - Egress

            ####################################################
            # INGRESS: Allow OpenShift Router only
            ####################################################
            ingress:
              - from:
                  - namespaceSelector:
                      matchLabels:
                        kubernetes.io/metadata.name: "{{ ingress_namespace }}"
                ports:
                  - protocol: TCP
                    port: "{{ app_port }}"

            ####################################################
            # EGRESS: Allow DNS + Internal Networks ONLY
            ####################################################
            egress:
              # DNS (required)
              - to:
                  - namespaceSelector:
                      matchLabels:
                        kubernetes.io/metadata.name: openshift-dns
                ports:
                  - protocol: UDP
                    port: 53
                  - protocol: TCP
                    port: 53

              # Internal cluster networks
              - to:
                  - ipBlock:
                      cidr: 10.0.0.0/8
              - to:
                  - ipBlock:
                      cidr: 172.16.0.0/12
              - to:
                  - ipBlock:
                      cidr: 192.168.0.0/16
